# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: suggestions.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'suggestions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11suggestions.proto\x12\x0b\x62ooksuggest\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"L\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x13\n\x0b\x62ook_tokens\x18\x03 \x03(\t\"N\n\x16RecommendationResponse\x12\x34\n\x0frecommendations\x18\x01 \x03(\x0b\x32\x1b.booksuggest.Recommendation\"[\n\x0eRecommendation\x12\x1f\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x11.booksuggest.Book\x12\x18\n\x10\x63onfidence_score\x18\x02 \x01(\x02\x12\x0e\n\x06reason\x18\x03 \x01(\t\"\x88\x01\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x0e\n\x06genres\x18\x06 \x03(\t\x12\x30\n\x0cpublish_date\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2k\n\x0e\x42ookSuggestion\x12Y\n\x0eGetSuggestions\x12\".booksuggest.RecommendationRequest\x1a#.booksuggest.RecommendationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=96
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=172
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=174
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=252
  _globals['_RECOMMENDATION']._serialized_start=254
  _globals['_RECOMMENDATION']._serialized_end=345
  _globals['_BOOK']._serialized_start=348
  _globals['_BOOK']._serialized_end=484
  _globals['_BOOKSUGGESTION']._serialized_start=486
  _globals['_BOOKSUGGESTION']._serialized_end=593
# @@protoc_insertion_point(module_scope)
