# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud_detection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'fraud_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x0f\x66raud_Detection\x1a\x1cgoogle/protobuf/struct.proto\"\x9e\x01\n\x10\x46raudInitRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x01\x12\x12\n\nip_address\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x17\n\x0f\x62illing_country\x18\x04 \x01(\t\x12\x14\n\x0c\x62illing_city\x18\x05 \x01(\t\x12\x16\n\x0epayment_method\x18\x06 \x01(\t\x12\x10\n\x08order_id\x18\x07 \x01(\t\"$\n\x11\x46raudInitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x9a\x01\n\x0c\x46raudRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x01\x12\x12\n\nip_address\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x17\n\x0f\x62illing_country\x18\x04 \x01(\t\x12\x14\n\x0c\x62illing_city\x18\x05 \x01(\t\x12\x16\n\x0epayment_method\x18\x06 \x01(\t\x12\x10\n\x08order_id\x18\x07 \x01(\t\"u\n\rFraudResponse\x12\x19\n\x11\x66raud_probability\x18\x01 \x01(\x01\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12(\n\x07\x64\x65tails\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x0f\n\x07reasons\x18\x04 \x03(\t2\xbe\x01\n\x15\x46raudDetectionService\x12X\n\x0fInitializeOrder\x12!.fraud_Detection.FraudInitRequest\x1a\".fraud_Detection.FraudInitResponse\x12K\n\nCheckFraud\x12\x1d.fraud_Detection.FraudRequest\x1a\x1e.fraud_Detection.FraudResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAUDINITREQUEST']._serialized_start=73
  _globals['_FRAUDINITREQUEST']._serialized_end=231
  _globals['_FRAUDINITRESPONSE']._serialized_start=233
  _globals['_FRAUDINITRESPONSE']._serialized_end=269
  _globals['_FRAUDREQUEST']._serialized_start=272
  _globals['_FRAUDREQUEST']._serialized_end=426
  _globals['_FRAUDRESPONSE']._serialized_start=428
  _globals['_FRAUDRESPONSE']._serialized_end=545
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=548
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=738
# @@protoc_insertion_point(module_scope)
