# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_executor/order_executor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'order_executor/order_executor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#order_executor/order_executor.proto\x12\x0eorder_executor\" \n\x0cOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"\x1f\n\rOrderResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\\\n\rOrderExecutor\x12K\n\x0c\x45xecuteOrder\x12\x1c.order_executor.OrderRequest\x1a\x1d.order_executor.OrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_executor.order_executor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERREQUEST']._serialized_start=55
  _globals['_ORDERREQUEST']._serialized_end=87
  _globals['_ORDERRESPONSE']._serialized_start=89
  _globals['_ORDERRESPONSE']._serialized_end=120
  _globals['_ORDEREXECUTOR']._serialized_start=122
  _globals['_ORDEREXECUTOR']._serialized_end=214
# @@protoc_insertion_point(module_scope)
