# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x0eorder_executor\"?\n\nJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12\x10\n\x08priority\x18\x03 \x01(\x05\"1\n\x0bJobResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tleader_id\x18\x02 \x01(\t\"#\n\x0eLeaderResponse\x12\x11\n\tleader_id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"d\n\x0fRequestVoteArgs\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x05\x12\x15\n\rlast_log_term\x18\x04 \x01(\x05\"7\n\x11RequestVoteResult\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"\x8b\x01\n\x11\x41ppendEntriesArgs\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x05\x12\x15\n\rprev_log_term\x18\x04 \x01(\x05\x12\x0f\n\x07\x65ntries\x18\x05 \x03(\x0c\x12\x15\n\rleader_commit\x18\x06 \x01(\x05\"4\n\x13\x41ppendEntriesResult\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\x99\x01\n\rClientService\x12\x44\n\tSubmitJob\x12\x1a.order_executor.JobRequest\x1a\x1b.order_executor.JobResponse\x12\x42\n\tGetLeader\x12\x15.order_executor.Empty\x1a\x1e.order_executor.LeaderResponse2\xbc\x02\n\x04Raft\x12Q\n\x0bRequestVote\x12\x1f.order_executor.RequestVoteArgs\x1a!.order_executor.RequestVoteResult\x12W\n\rAppendEntries\x12!.order_executor.AppendEntriesArgs\x1a#.order_executor.AppendEntriesResult\x12\x44\n\tSubmitJob\x12\x1a.order_executor.JobRequest\x1a\x1b.order_executor.JobResponse\x12\x42\n\tGetLeader\x12\x15.order_executor.Empty\x1a\x1e.order_executor.LeaderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOBREQUEST']._serialized_start=30
  _globals['_JOBREQUEST']._serialized_end=93
  _globals['_JOBRESPONSE']._serialized_start=95
  _globals['_JOBRESPONSE']._serialized_end=144
  _globals['_LEADERRESPONSE']._serialized_start=146
  _globals['_LEADERRESPONSE']._serialized_end=181
  _globals['_EMPTY']._serialized_start=183
  _globals['_EMPTY']._serialized_end=190
  _globals['_REQUESTVOTEARGS']._serialized_start=192
  _globals['_REQUESTVOTEARGS']._serialized_end=292
  _globals['_REQUESTVOTERESULT']._serialized_start=294
  _globals['_REQUESTVOTERESULT']._serialized_end=349
  _globals['_APPENDENTRIESARGS']._serialized_start=352
  _globals['_APPENDENTRIESARGS']._serialized_end=491
  _globals['_APPENDENTRIESRESULT']._serialized_start=493
  _globals['_APPENDENTRIESRESULT']._serialized_end=545
  _globals['_CLIENTSERVICE']._serialized_start=548
  _globals['_CLIENTSERVICE']._serialized_end=701
  _globals['_RAFT']._serialized_start=704
  _globals['_RAFT']._serialized_end=1020
# @@protoc_insertion_point(module_scope)
